name: Work 2 Alberto
on:
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Print Something
      run:
        echo "Print 1"
        echo "Print 2"
        echo "Print 3"
